plugins {
    id 'com.android.application'
}
apply plugin: 'kotlin-android'

android {
    namespace 'com.niu.autopilot'
    compileSdk 34

    defaultConfig {
        applicationId "com.niu.autopilot"
        minSdk 26
        targetSdk 34
        versionCode 76
        versionName "2.74"
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    // v1.1 车辆动画组件依赖
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
}
